version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "9191:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: on-failure

volumes:
  jenkins_home:
